# Generated by Django 5.1.3 on 2024-11-14 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.CharField(max_length=500)),
                ('duracion', models.DurationField()),
                ('clasifiacion', models.CharField(max_length=3)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_estreno', models.DateField()),
                ('estado_peliculas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Productos_confiteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descrpcion_producto', models.CharField(max_length=100)),
                ('precio_producto', models.CharField(max_length=20)),
                ('stock_producto', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.CharField(max_length=2)),
                ('numero_butaca', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_funcion', models.DateField()),
                ('hora_funcion', models.TimeField()),
                ('precio_funcion', models.IntegerField(default=1)),
                ('id_peliculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.peliculas')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.CharField(max_length=2)),
                ('estado_ticket', models.CharField(max_length=10)),
                ('dia_expiracion', models.CharField(max_length=20)),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.funciones')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peliculas_carrito', models.CharField(max_length=10)),
                ('confiteria_carrito', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('estado_venta', models.CharField(max_length=10)),
                ('id_confiteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.productos_confiteria')),
                ('id_tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.tickets')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.usuarios')),
            ],
        ),
    ]
