# Generated by Django 5.1.3 on 2024-11-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='valor_peliculas',
            field=models.IntegerField(default=3000, max_length=10),
            preserve_default=False,
        ),
    ]
