# Generated by Django 5.1.3 on 2024-11-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0005_descuentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='director',
            field=models.CharField(default='Dhako', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='imagen_url',
            field=models.CharField(default='https://m.media-amazon.com/images/I/81fxZOlyEBL._AC_UF1000,1000_QL80_.jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='reparto',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='titulo_original',
            field=models.CharField(default='Titulo completo pelicula', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='trailer_url',
            field=models.CharField(default='https://www.youtube.com/watch?v=wuXjTZjYZQY&ab_channel=SonyPicturesEspa%C3%B1a', max_length=500),
            preserve_default=False,
        ),
    ]
